In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/Users/vic/Desktop/Churn Prediction/Data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
data

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [3]:
data['TotalCharges']=pd.to_numeric(data['TotalCharges'],errors='coerce')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
data.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [6]:
data.dropna()

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95       1889.50   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80       1990.50   
7039              Yes    Credit card (automatic)         103.20       7362.90   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40        306.60   
7042              Yes  Bank transfer (automatic)         105.65       6844.50   

      Churn  
0        No  
1        No  
2       Yes  
3        No  
4       Yes  
...     ...  
7038     No  
7039     No  
7040     No  
7041    Yes  
7042     No  

[7032 rows x 21 columns]

In [7]:
data=data.dropna(subset='TotalCharges')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   object 
 1   gender            7032 non-null   object 
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   object 
 4   Dependents        7032 non-null   object 
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   object 
 7   MultipleLines     7032 non-null   object 
 8   InternetService   7032 non-null   object 
 9   OnlineSecurity    7032 non-null   object 
 10  OnlineBackup      7032 non-null   object 
 11  DeviceProtection  7032 non-null   object 
 12  TechSupport       7032 non-null   object 
 13  StreamingTV       7032 non-null   object 
 14  StreamingMovies   7032 non-null   object 
 15  Contract          7032 non-null   object 
 16  PaperlessBilling  7032 non-null   object 
 17  

In [11]:
data=data.drop('customerID',axis=1)
data=pd.get_dummies(data,drop_first=True)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   SeniorCitizen                          7032 non-null   int64  
 1   tenure                                 7032 non-null   int64  
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   gender_Male                            7032 non-null   bool   
 5   Partner_Yes                            7032 non-null   bool   
 6   Dependents_Yes                         7032 non-null   bool   
 7   PhoneService_Yes                       7032 non-null   bool   
 8   MultipleLines_No phone service         7032 non-null   bool   
 9   MultipleLines_Yes                      7032 non-null   bool   
 10  InternetService_Fiber optic            7032 non-null   bool   
 11  InternetS

In [15]:
from sklearn.model_selection import train_test_split
X=data.drop('Churn_Yes',axis=1)
y=data['Churn_Yes']

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [42]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,Y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [43]:
from sklearn.metrics import confusion_matrix,classification_report,roc_auc_score
Y_pred=lr.predict(X_test)
Y_prob=lr.predict_proba(X_test)[:,1]
print("Confusion Matrix:\n",confusion_matrix(Y_test,Y_pred))
print("\nClassification report:\n",classification_report(Y_test,Y_pred))
print("\nROC_AUC_SCORE:\n",roc_auc_score(Y_test,Y_prob))

Confusion Matrix:
 [[916 117]
 [160 214]]

Classification report:
               precision    recall  f1-score   support

       False       0.85      0.89      0.87      1033
        True       0.65      0.57      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407


ROC_AUC_SCORE:
 0.8364907258335879


In [44]:
threshold=[0.3,0.4]
for t in threshold:
    y_pred1=(Y_prob>=t).astype(int)
    print(f"\nThreshold={t}:")
    print(confusion_matrix(Y_test, y_pred1))
    print(classification_report(Y_test, y_pred1))


Threshold=0.3:
[[765 268]
 [ 90 284]]
              precision    recall  f1-score   support

       False       0.89      0.74      0.81      1033
        True       0.51      0.76      0.61       374

    accuracy                           0.75      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.79      0.75      0.76      1407


Threshold=0.4:
[[846 187]
 [119 255]]
              precision    recall  f1-score   support

       False       0.88      0.82      0.85      1033
        True       0.58      0.68      0.62       374

    accuracy                           0.78      1407
   macro avg       0.73      0.75      0.74      1407
weighted avg       0.80      0.78      0.79      1407



In [25]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)
rf.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=42)

In [26]:
Y_pred=rf.predict(X_test)
Y_prob=rf.predict_proba(X_test)[:,1]
print("Confusion Matrix:\n",confusion_matrix(Y_test,Y_pred))
print("\nClassification report:\n",classification_report(Y_test,Y_pred))
print("\nROC_AUC_SCORE:\n",roc_auc_score(Y_test,Y_prob))

Confusion Matrix:
 [[926 107]
 [185 189]]

Classification report:
               precision    recall  f1-score   support

       False       0.83      0.90      0.86      1033
        True       0.64      0.51      0.56       374

    accuracy                           0.79      1407
   macro avg       0.74      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407


ROC_AUC_SCORE:
 0.8193672963333007


In [29]:
threshold=[0.3,0.4]
for t in threshold:
    y_pred1=(Y_prob>=t).astype(int)
    print(f"\nThreshold={t}:")
    print(confusion_matrix(Y_test, y_pred1))
    print(classification_report(Y_test, y_pred1))



Threshold=0.3:
[[777 256]
 [101 273]]
              precision    recall  f1-score   support

       False       0.88      0.75      0.81      1033
        True       0.52      0.73      0.60       374

    accuracy                           0.75      1407
   macro avg       0.70      0.74      0.71      1407
weighted avg       0.79      0.75      0.76      1407


Threshold=0.4:
[[863 170]
 [151 223]]
              precision    recall  f1-score   support

       False       0.85      0.84      0.84      1033
        True       0.57      0.60      0.58       374

    accuracy                           0.77      1407
   macro avg       0.71      0.72      0.71      1407
weighted avg       0.78      0.77      0.77      1407



In [31]:
!pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 45.2 MB/s eta 0:00:00


In [34]:
from xgboost import XGBClassifier
scale_pos_weight=Y_train.value_counts()[0]/Y_train.value_counts()[1]
scale_pos_weight

/var/folders/kj/v7g1f0q1627f8hff1l1gmh6r0000gn/T/ipykernel_13811/1472607495.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  scale_pos_weight=Y_train.value_counts()[0]/Y_train.value_counts()[1]


np.float64(2.762541806020067)

In [37]:
xg=XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.5,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric="logloss"
)
xg.fit(X_train,Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.5, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [38]:
Y_pred=xg.predict(X_test)
Y_prob=xg.predict_proba(X_test)[:,1]
print("Confusion Matrix:\n",confusion_matrix(Y_test,Y_pred))
print("\nClassification report:\n",classification_report(Y_test,Y_pred))
print("\nROC_AUC_SCORE:\n",roc_auc_score(Y_test,Y_prob))

Confusion Matrix:
 [[839 194]
 [149 225]]

Classification report:
               precision    recall  f1-score   support

       False       0.85      0.81      0.83      1033
        True       0.54      0.60      0.57       374

    accuracy                           0.76      1407
   macro avg       0.69      0.71      0.70      1407
weighted avg       0.77      0.76      0.76      1407


ROC_AUC_SCORE:
 0.7885746307675583


In [41]:
threshold=[0.3,0.4]
for t in threshold:
    y_pred1=(Y_prob>=t).astype(int)
    print(f"\nThreshold={t}:")
    print(confusion_matrix(Y_test, y_pred1))
    print(classification_report(Y_test, y_pred1))


Threshold=0.3:
[[789 244]
 [116 258]]
              precision    recall  f1-score   support

       False       0.87      0.76      0.81      1033
        True       0.51      0.69      0.59       374

    accuracy                           0.74      1407
   macro avg       0.69      0.73      0.70      1407
weighted avg       0.78      0.74      0.75      1407


Threshold=0.4:
[[813 220]
 [134 240]]
              precision    recall  f1-score   support

       False       0.86      0.79      0.82      1033
        True       0.52      0.64      0.58       374

    accuracy                           0.75      1407
   macro avg       0.69      0.71      0.70      1407
weighted avg       0.77      0.75      0.76      1407



In [45]:
!pip install streamlit

In [47]:
risk_df = X_test.copy()
risk_df['Churn_Probability'] = Y_prob

risk_df['Risk_Level'] = pd.cut(
    risk_df['Churn_Probability'],
    bins=[0, 0.3, 0.6, 1.0],
    labels=['Low Risk', 'Medium Risk', 'High Risk']
)

In [50]:
risk_df

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
974               0      59           75.95       4542.35        False   
619               0       7           78.55        522.95        False   
4289              0      54           20.10       1079.45        False   
3721              0       2           20.65         38.70        False   
4533              0      71          105.15       7555.00        False   
...             ...     ...             ...           ...          ...   
4829              0      12           45.00        524.35        False   
5176              0      26           45.80       1147.00        False   
2750              0       3           19.45         69.25         True   
4432              0      37           40.55       1390.85         True   
2091              0      50           20.15        970.85        False   

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
974          True            True              True   
619         False           False              True   
4289        False           False              True   
3721        False           False              True   
4533         True           False              True   
...           ...             ...               ...   
4829        False           False              True   
5176        False            True             False   
2750        False           False              True   
4432        False           False             False   
2091        False            True              True   

      MultipleLines_No phone service  MultipleLines_Yes  ...  \
974                            False              False  ...   
619                            False               True  ...   
4289                           False              False  ...   
3721                           False              False  ...   
4533                           False               True  ...   
...                              ...                ...  ...   
4829                           False              False  ...   
5176                            True              False  ...   
2750                           False              False  ...   
4432                            True              False  ...   
2091                           False              False  ...   

      StreamingMovies_Yes  Contract_One year  Contract_Two year  \
974                  True              False               True   
619                 False              False              False   
4289                False              False               True   
3721                False              False              False   
4533                 True              False               True   
...                   ...                ...                ...   
4829                False              False              False   
5176                 True              False              False   
2750                False               True              False   
4432                False              False               True   
2091                False              False               True   

      PaperlessBilling_Yes  PaymentMethod_Credit card (automatic)  \
974                   True                                   True   
619                   True                                  False   
4289                 False                                  False   
3721                 False                                  False   
4533                  True                                  False   
...                    ...                                    ...   
4829                  True                                  False   
5176                 False                                  False   
2750                  True                                  False   
4432                  True                                  False   
2091                 False                                   True   

      PaymentMethod_Electronic check  PaymentMethod_M

In [49]:
risk_df['Actual_Churn'] = Y_test.values

In [54]:
risk_df.to_csv("/Users/vic/Desktop/Churn Prediction/Data/risk_output.csv", index=False)

In [57]:
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Churn Risk Dashboard", layout="wide")

st.title("📊 Customer Churn Risk Dashboard")

# Load data (you can pickle model later)
risk_df = pd.read_csv("/Users/vic/Desktop/Churn Prediction/Data/risk_output.csv")  # we will create this

# ---- KPIs ----
total_customers = len(risk_df)
churn_rate = risk_df['Actual_Churn'].mean() * 100
high_risk_pct = (risk_df['Risk_Level'] == 'High Risk').mean() * 100

col1, col2, col3 = st.columns(3)
col1.metric("Total Customers", total_customers)
col2.metric("Churn Rate (%)", f"{churn_rate:.2f}")
col3.metric("High Risk Customers (%)", f"{high_risk_pct:.2f}")

st.divider()

# ---- Risk Distribution ----
st.subheader("🔍 Churn Risk Distribution")

risk_counts = risk_df['Risk_Level'].value_counts()

fig, ax = plt.subplots()
risk_counts.plot(kind='bar', ax=ax)
ax.set_xlabel("Risk Level")
ax.set_ylabel("Number of Customers")
st.pyplot(fig)

# ---- Churn Probability Distribution ----
st.subheader("📈 Churn Probability Distribution")

fig2, ax2 = plt.subplots()
ax2.hist(risk_df['Churn_Probability'], bins=20)
ax2.set_xlabel("Churn Probability")
ax2.set_ylabel("Customers")
st.pyplot(fig2)

# ---- High Risk Customers ----
st.subheader("🚨 High Risk Customers")

high_risk_df = risk_df[risk_df['Risk_Level'] == 'High Risk']
st.dataframe(high_risk_df.head(20))

2025-12-17 18:25:57.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-12-17 18:25:57.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

DeltaGenerator()

In [59]:
risk_df.to_csv("/Users/vic/Desktop/Churn Prediction/Data/risk_output.csv", index=False)

In [61]:
import os
os.getcwd()

'/Users/vic/Desktop/Churn Prediction/Notebook'